### PR TITLE
Add Ruby 3.3.0 support

### PR DESCRIPTION
**Pull request by torrocus**
Initial support for Ruby 3.3

## Feedback

I followed the changes for Ruby 3.2, I hope I went in the right direction. Unfortunately, the tests are not yet passed. I will gladly accept help.

### CODE REVIEW

**Comment by torrocus** [comment]
@zenspider I saw that you changed some filenames, so I resolved the conflicts and rebased the code.

**Comment by torrocus** [comment]
@zenspider Today I did a rebase again and resolved the conflicts.

**Comment by zenspider** [comment]
I've been working on the same thing. We probably have nearly identical diffs at this point. If you only have 2 failing tests due to error message not quite matching I fixed it with this:

```ruby
assert_match(/parse error on value \S+ ..end./, e.message)
```

It is a difference in bison vs lrama error handling I guess?

**Comment by zenspider** [comment]
Done! Thanks! I'll get a release out shortly... trying to see if I can improve `rake compare` first.

**Pull request closed without merging**
