### PR TITLE
Improve compatibility on tokenizing number

### PR DESCRIPTION
**Pull request by soutaro**
This PR is to make tokenizing numbers more compatible with ruby. The motivating example is the following:

```rb
1.0if true
```

This parses by ruby as floating point literal with `if` modifier. However, `ruby_parser` fails tokenizing it as `Bad number format`. I understand the behavior is to help debugging, but also makes the parser incompatible.

With this PR, it parses same as ruby.

This introduces incompatibilities with older versions of ruby_parser. I think it is okay, because currently parsing Ruby programs continue to parse, and some ruby-incompatibly rejected programs will parse with this patch.

I know this patch itself does not make much sense, because we usually put a space before `if`. This is something like a stepping stone to improve compatibility of #228.

### CODE REVIEW

**Comment by zenspider** [comment]
Beautiful. Thank you.

**Comment by zenspider** [comment]
This one doesn't apply cleanly after #228 went in. I had one hunk on the FLOAT constant collide. It is failing 3 tests with errors:

```
  1) Error:
TestRubyLexer#test_yylex_float_e_bad_double_e:
RubyParser::SyntaxError: Bad number format. near line 1: "e2e3"

  2) Error:
TestRubyLexer#test_yylex_float_if_modifier:
RubyParser::SyntaxError: Bad number format. near line 1: "e2if"

  3) Error:
TestRuby23Parser#test_float_with_if_modifier:
RubyParser::SyntaxError: no .<digit> floating literal anymore put 0 before dot. near line 1: "if true"
```

**Comment by zenspider** [comment]
And if I hand apply the new float constant, the tests from #228 fail.

Can you `rebase` and `push -f`?

**Comment by zenspider** [comment]
OK. One last attempt. I hand modified `FLOAT` to remove the `\b`s from the version from #228. Now I have these failures:

```
  1) Error:
TestRuby23Parser#test_float_with_if_modifier:
Racc::ParseError: (string):1 :: parse error on value "f" (tIDENTIFIER)
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb:529:in `on_error'
    /Users/ryan/Work/p4/zss/src/ruby_parser/dev/lib/ruby_parser_extras.rb:1227:in `on_error'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb:258:in `_racc_do_parse_c'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb:258:in `do_parse'
    /Users/ryan/Work/p4/zss/src/ruby_parser/dev/lib/ruby_parser_extras.rb:1139:in `block in process'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    /Users/ryan/Work/p4/zss/src/ruby_parser/dev/lib/ruby_parser_extras.rb:1127:in `process'
    /Users/ryan/Work/p4/zss/src/ruby_parser/dev/test/test_ruby_parser.rb:44:in `assert_parse'
    /Users/ryan/Work/p4/zss/src/ruby_parser/dev/test/test_ruby_parser.rb:3573:in `test_float_with_if_modifier'


  2) Failure:
TestRubyLexer#test_yylex_float_if_modifier [/Users/ryan/Work/p4/zss/src/ruby_parser/dev/test/test_ruby_lexer.rb:979]:
[:tFLOAT, 100, :expr_end, nil, nil] vs [:tIMAGINARY, (0+100.0i), :expr_end, 0, 0].
Expected: :tFLOAT
  Actual: :tIMAGINARY
```

So the first one is swallowing the `i` in `if` and then blowing up. I assume the second one is doing the same. Suggestions?

**Comment by zenspider** [comment]
ugh... Please review:

```ruby
  FLOAT         /[+]?\d[\d_]*\.[\d_]+(e[+-]?[\d_]+)?(?:(ri|r|i)\b)?|[+]?[\d_]+e[+-]?[\d_]+(?:(ri|r|i)\b)?/i
```

**Comment by zenspider** [comment]
Sometimes I hate ruby:

```ruby
>> 1e2if true
=> 100.0
>> 1e2i if true
=> (0+100.0i)
>> 1e2iif true
SyntaxError: (irb):3: syntax error, unexpected tIDENTIFIER, expecting end-of-input
1e2iif true
      ^
	from /Users/ryan/.rbenv/versions/2.3.1-static/bin/irb:11:in `<main>'
```

**Comment by soutaro** [comment]
Thanks! The grouping regex looks perfect!

I will rebase and revise the tokenizing regexps this weekend, maybe... (or will you do that yourself?)

**Comment by zenspider** [comment]
OK. I've manually applied this with my changes. Thanks! Sorry it took me so long.

**Pull request closed without merging**
