### PR TITLE
Add failing test for parsing defs kwarg

### PR DESCRIPTION
**Pull request by presidentbeef**
From https://github.com/presidentbeef/brakeman/issues/654#issuecomment-100382158

### CODE REVIEW

**Comment by zenspider** [comment]
Fantastic. Thanks!

**Comment by kbrock** [comment]
nice - merge?

**Comment by presidentbeef** [comment]
This is just a test to demonstrate the issue, not a fix.

**Comment by presidentbeef** [comment]
There was an existing test for this, so closing in favor of #204.

**Pull request closed without merging**
