### PR TITLE
Add test for slashy newlines in strings

### PR DESCRIPTION
**Pull request by maxjacobson**
Reproduces https://github.com/seattlerb/ruby_parser/issues/222 cc @ABaldwinHunter

### CODE REVIEW

**Comment by zenspider** [comment]
Can you spot check that the following change to your test looks correct?

```ruby
  def test_slashy_newlines_within_string
    rb = %(puts "hello\
 my\
 dear\
 friend"

a + b
    )

    pt = s(:block,
            s(:call, nil, :puts, s(:str, "hello my dear friend").line(1)).line(1),
            s(:call, s(:call, nil, :a).line(6),
              :+,
              s(:call, nil, :b).line(6)).line(6)
          ).line(1)

    assert_parse rb, pt
  end
```

**Comment by maxjacobson** [comment]
Hey, awesome! Yeah, it definitely does.

I'm glad to see that it now finds the `a + b` part correctly to be on line 6 of the program.

The only thing I'm wondering now is whether it's correct to be seeing the string as fully being on line 1, when in reality it's split over lines 1-4 (so is the `call` to puts).

**Comment by presidentbeef** [comment]
FWIW I think it's fine to consider the line number of the string to be the line on which it starts. That seems more logical to me than the ending line. Of course, both would be best but that's not how RubyParser works at the moment.

**Comment by zenspider** [comment]
This is now in w/ my changes and passing. Thanks!

**Comment by maxjacobson** [comment]
Sweet, thanks!

**Comment by ABaldwinHunter** [comment]
Nice! Thanks

**Pull request closed without merging**
