### PR TITLE
Fix timeout on long strings of backslashes

### PR DESCRIPTION
**Pull request by presidentbeef**
Another regex performance problem solved by atomic groups!

Since `(\\.|[^\'])` will either match `\\.` or `[^\']` there should be no need to try the second if the first already matched.

Without this change, it will time out on moderately long strings containing backslashes.

### CODE REVIEW

**Comment by zenspider** [comment]
Even if I extend out the multiplier from 100 to 100_000, I don't see a delay at all in running that test. When I extend it to 1_000_000, I get a delay:

```
TestRuby20Parser#test_str_backslashes = 0.28 s = .
TestRuby22Parser#test_str_backslashes = 0.38 s = .
TestRuby21Parser#test_str_backslashes = 0.22 s = .
TestRuby19Parser#test_str_backslashes = 0.24 s = .
TestRuby18Parser#test_str_backslashes = 0.21 s = .
```

But that is without your change to the lexer. If I add your patch, the times don't really change:

```
TestRuby18Parser#test_str_backslashes = 0.27 s = .
TestRuby20Parser#test_str_backslashes = 0.20 s = .
TestRuby19Parser#test_str_backslashes = 0.21 s = .
TestRuby22Parser#test_str_backslashes = 0.29 s = .
TestRuby21Parser#test_str_backslashes = 0.22 s = .
```

So, is the test setup bad? Or is the implementation bad? This is one of those wierd ones where you're having to muck with large amounts of memory so it gets hard to tell.

**Comment by presidentbeef** [comment]
You don't need to use large amounts of memory to reproduce.

```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
$ cat test.rb 
a 'a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a\\a'
$ ruby_parse test.rb 
# file = test.rb loc = 1
/home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_lexer.rex.rb:166:in `scan' #<Timeout::Error: execution expired> for test.rb
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_lexer.rex.rb:166:in `scan'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_lexer.rex.rb:166:in `next_token'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919:in `next_token'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:1036:in `block in process'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
  /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:1024:in `process'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:1362:in `block in process'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:1360:in `each'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:1360:in `process'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/bin/ruby_parse:48:in `block in <top (required)>'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/bin/ruby_parse:29:in `each'
  /home/justin/.rvm/gems/ruby-2.2.1@test/gems/ruby_parser-3.7.0/bin/ruby_parse:29:in `<top (required)>'
  /home/justin/.rvm/gems/ruby-2.2.1@test/bin/ruby_parse:23:in `load'
  /home/justin/.rvm/gems/ruby-2.2.1@test/bin/ruby_parse:23:in `<main>'
  /home/justin/.rvm/gems/ruby-2.2.1@test/bin/ruby_executable_hooks:15:in `eval'
  /home/justin/.rvm/gems/ruby-2.2.1@test/bin/ruby_executable_hooks:15:in `<main>'
done


10.00s:     0.10 l/s:    0.03 Kb/s:    0 Kb:    1 loc:test.rb

10.00s:     0.10 l/s:    0.03 Kb/s:    0 Kb:    1 loc:TOTAL
```

**Comment by presidentbeef** [comment]
Test definitely times out for me if I undo the code change:

```
$ rake
racc -v -l -o lib/ruby18_parser.rb lib/ruby18_parser.y
racc -v -l -o lib/ruby19_parser.rb lib/ruby19_parser.y
11 useless nonterminals
11 useless rules
unifdef -tk -DRUBY20 -URUBY21 -URUBY22 -UDEAD lib/ruby_parser.yy > lib/ruby20_parser.y || true
racc -v -l -o lib/ruby20_parser.rb lib/ruby20_parser.y
11 useless nonterminals
11 useless rules
2 shift/reduce conflicts
unifdef -tk -URUBY20 -DRUBY21 -URUBY22 -UDEAD lib/ruby_parser.yy > lib/ruby21_parser.y || true
racc -v -l -o lib/ruby21_parser.rb lib/ruby21_parser.y
11 useless nonterminals
11 useless rules
2 shift/reduce conflicts
unifdef -tk -URUBY20 -URUBY21 -DRUBY22 -UDEAD lib/ruby_parser.yy > lib/ruby22_parser.y || true
racc -v -l -o lib/ruby22_parser.rb lib/ruby22_parser.y
11 useless nonterminals
11 useless rules
2 shift/reduce conflicts
Generating lib/ruby_lexer.rex.rb from lib/ruby_lexer.rex from 2.4.0
/home/justin/.rvm/rubies/ruby-2.2.1/bin/ruby -w -I../../oedipus_lex/dev/lib:../../minitest/dev/lib:../../sexp_processor/dev/lib:lib:bin:test:. -e 'require "rubygems"; gem "minitest"; require "minitest/autorun"; require "test/test_ruby_parser_extras.rb"; require "test/test_ruby_parser.rb"; require "test/test_ruby_lexer.rb"' -- 


Run options: --seed 51676

# Running:

........................................................................................................................................................................................................................................E...............................................................................S...................................................S...................................S....................................................................................................................................................................................................................................................................................................................................................S.....................................................................................................................................................................................................................................................................................SS...........S................S...................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..........................................................................................................................S.......................................................................................................................................................S.........................................................................................................................................................................................................................................................................................................S.............................................................................................................................................................................................................................................................S......................................................................................S...................................................................................................................................................S....................................................................................S...................................................................................................................................................................................................................................................................................................................................................................................S.........S.................................................................................................................................................................................................................................................................................................................................................S................................................................................................................................................................................................................................................................................

Finished in 11.615034s, 313.4730 runs/s, 1537.3179 assertions/s.

  1) Error:
TestRuby22Parser#test_str_backslashes:
Timeout::Error: execution expired
    /home/justin/scratch/ruby_parser/lib/ruby_lexer.rex.rb:166:in `scan'
    /home/justin/scratch/ruby_parser/lib/ruby_lexer.rex.rb:166:in `next_token'
    /home/justin/scratch/ruby_parser/lib/ruby_parser_extras.rb:919:in `next_token'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
    /home/justin/scratch/ruby_parser/lib/ruby_parser_extras.rb:1036:in `block in process'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    /home/justin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
    /home/justin/scratch/ruby_parser/lib/ruby_parser_extras.rb:1024:in `process'
    /home/justin/scratch/ruby_parser/test/test_ruby_parser.rb:44:in `assert_parse'
    /home/justin/scratch/ruby_parser/test/test_ruby_parser.rb:583:in `test_str_backslashes'

3641 runs, 17856 assertions, 0 failures, 1 errors, 19 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [/home/justin/.rvm/rubies/ruby-2.2.1/bin/ru...]
/home/justin/.rvm/gems/ruby-2.2.1@ruby_parser/gems/hoe-3.13.1/lib/hoe/test.rb:83:in `block in define_test_tasks'
/home/justin/.rvm/gems/ruby-2.2.1@ruby_parser/bin/ruby_executable_hooks:15:in `eval'
/home/justin/.rvm/gems/ruby-2.2.1@ruby_parser/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by zenspider** [comment]
This is fixed. Thanks!

**Comment by zenspider** [comment]
@presidentbeef please review alternative: https://gist.github.com/2da9b636f5ecc7894163

**Pull request closed without merging**
