### PR TITLE
Take exactly 4 hex chars for bare unicode escape

### PR DESCRIPTION
**Pull request by mvz**
This fixes parsing of strings like `"\u1234ab"`, where RubyParser currently drops the `ab` on the floor.

### CODE REVIEW

**Comment by zenspider** [comment]
Hrm... I'm happy to merge your patch as-is, but this makes me think that there are still edge cases:

```c
    if (wide ? (numlen == 0 || numlen > 6) : (numlen < 4))  {
        yyerror0("invalid Unicode escape");
        return wide && numlen > 0;
    }
```

**Comment by mvz** [comment]
I'll take a look at those edge cases soonish. It would be good to have them handled as well.

**Comment by mvz** [comment]
It seems this unescape is done in several places. I'll cover those as well.

**Comment by zenspider** [comment]
Added. Thank you!

**Pull request closed without merging**
