### PR TITLE
Create a GitHub Actions workflow to run tests

### PR DESCRIPTION
**Pull request by torrocus**
We have to run tests locally. I added ability to run tests on GitHub CI.

## Feedback

Checked on the local fork and everything works. :tada:

### CODE REVIEW

**Comment by torrocus** [comment]
@zenspider I think it's worth merging it before merging other PRs.

**Comment by torrocus** [comment]
@zenspider Take a look when you have some free time. I think this might be useful.

**Comment by torrocus** [comment]
Is there anything stopping you from merging this PR?

**Comment by zenspider** [comment]
calm down.

**Comment by zenspider** [comment]
Not gonna add. I don't want to use github any more than I have to. Besides, this project is (probably? hopefully?) being supplanted by prism in the future.

**Comment by torrocus** [comment]
Thank you @zenspider for your response, and I apologize if my previous comments seemed too persistent. I noticed that you are making other changes in this repository, leading me to believe that you might have overlooked this specific PR. I have good intentions and simply wanted to streamline the test running process.

I respect your approach to using GitHub, although it wasn't explicitly stated anywhere. My intentions were straightforward – I thought that incorporating these changes could automate the PR review process and encourage more collaboration on the project. Even if you are planning for "prism" to replace "ruby_parser" in the future, it's challenging to predict when that transition might occur.

Could you share the reason why all the PRs are closed without being merged? I see that some changes from PRs are in the master branch commits. However, none of the authors are included in the list of contributors. It's possible I'm missing something. I couldn't find an answer to this question, so I would appreciate a better understanding of the situation.

**Pull request closed without merging**
