### PR TITLE
Fix several line numbering issues

### PR DESCRIPTION
**Pull request by mvz**
- Fix line numbering for range literals
- Fix line numbering for right-hand side of multiple assignment

This changes the implementation of `s()` to inherit line numbers from its children if possible.

### CODE REVIEW

**Comment by presidentbeef** [comment]
Is there a performance/memory impact when scanning the children every time a new Sexp is created?

**Comment by mvz** [comment]
@presidentbeef a quick check shows that the whole test suite is about 3% slower.

**Comment by mvz** [comment]
Maybe it's better to go back to #288 and fix the assignment line numbers some other way :thinking:.

**Comment by zenspider** [comment]
Mmmm... I think I'm gonna push back on this one. I need to poke around a bit tho. I'd definitely like to keep the `ruby_parser.yy` change and probably the tests. I want to experiment with the egregious part tho to see if there isn't some middle ground.

**Comment by zenspider** [comment]
OK. I have a horrible patch that w/ an activating ENV var turns on a mode that checks the line numbers of all sexps at every parse reduce and raises if something doesn't have a line number OR if the current line number is bigger than the smallest line number of its contents.

I have 59 errors to fix just for `N=/V25/`, so this should drive out a lot of this, without a performance penalty for normal runs.

Lemme dig in and try to fix these... It'll probably cause some merge conflicts if it is widespread.

**Comment by zenspider** [comment]
RAWR! Killed them!

**Comment by zenspider** [comment]
Your tests pass without your fixes to `dot2`/`dot3` parsing... which makes me think they weren't covering the edge case properly?

**Comment by mvz** [comment]
All of the tests in this PR fail for me with current master?

**Comment by mvz** [comment]
These two cases are now handled by #288 and #294.

**Pull request closed without merging**
